import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QWidget, QGridLayout, QPushButton, QLabel, QVBoxLayout, QMessageBox
from PyQt6.QtGui import QPixmap
import random

class battleship(QWidget):






    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Battleship")
        MainWindow.resize(1124, 789)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        ################################## TITULOS ##########################################
        self.titulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(0, -20, 1121, 131))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.titulo.setFont(font)
        self.titulo.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.titulo.setAutoFillBackground(False)
        self.titulo.setStyleSheet("")
        self.titulo.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titulo.setOpenExternalLinks(False)
        self.titulo.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.titulo.setObjectName("titulo")
        self.titulo_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.titulo_2.setGeometry(QtCore.QRect(730, 220, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.titulo_2.setFont(font)
        self.titulo_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titulo_2.setObjectName("titulo_2")

        ######################################## BOTONES DE INICIO (Aleatorizar/Iniciar) #####################################
        self.gridLayoutWidget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(50, 70, 1021, 91))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.control = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.control.setContentsMargins(0, 0, 0, 0)
        self.control.setObjectName("control")
        self.aleatorizar_barcos = QtWidgets.QPushButton(parent=self.gridLayoutWidget_5)
        self.aleatorizar_barcos.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.aleatorizar_barcos.setFont(font)
        self.aleatorizar_barcos.setAutoFillBackground(True)
        self.aleatorizar_barcos.setCheckable(False)
        self.aleatorizar_barcos.setAutoRepeat(False)
        self.aleatorizar_barcos.setDefault(False)
        self.aleatorizar_barcos.setFlat(False)
        self.aleatorizar_barcos.setObjectName("aleatorizar_barcos")
        self.control.addWidget(self.aleatorizar_barcos, 0, 0, 1, 1)
        self.inicial_juego = QtWidgets.QPushButton(parent=self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.inicial_juego.setFont(font)
        self.inicial_juego.setAutoFillBackground(True)
        self.inicial_juego.setAutoDefault(False)
        self.inicial_juego.setDefault(False)
        self.inicial_juego.setFlat(False)
        self.inicial_juego.setObjectName("inicial_juego")
        self.control.addWidget(self.inicial_juego, 0, 2, 1, 1)
        

        ######################################## BOTON DE EXPLOSIÓN DE MATERIAL #####################################
        self.explosion = QtWidgets.QPushButton(parent=self.centralwidget)
        self.explosion.setGeometry(QtCore.QRect(740, 630, 331, 56))
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.explosion.setFont(font)
        self.explosion.setAutoFillBackground(True)
        self.explosion.setAutoDefault(False)
        self.explosion.setDefault(False)
        self.explosion.setFlat(False)
        self.explosion.setObjectName("explosion")
        
        

        ################################################# GRILLA DE BARCOS #######################################################

        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 192, 621, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grilla_barcos = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grilla_barcos.setContentsMargins(0, 0, 0, 0)
        self.grilla_barcos.setObjectName("grilla_barcos")
        self.label_11 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.grilla_barcos.addWidget(self.label_11, 1, 9, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.grilla_barcos.addWidget(self.label_12, 2, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.grilla_barcos.addWidget(self.label_14, 2, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_18.setText("")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.grilla_barcos.addWidget(self.label_18, 3, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.grilla_barcos.addWidget(self.label_16, 2, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_19.setText("")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.grilla_barcos.addWidget(self.label_19, 3, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.grilla_barcos.addWidget(self.label_15, 2, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.grilla_barcos.addWidget(self.label_17, 3, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.grilla_barcos.addWidget(self.label_20, 3, 8, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_21.setText("")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.grilla_barcos.addWidget(self.label_21, 3, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.grilla_barcos.addWidget(self.label_10, 1, 8, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.grilla_barcos.addWidget(self.label_6, 0, 9, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.grilla_barcos.addWidget(self.label_3, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.grilla_barcos.addWidget(self.label_4, 0, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.grilla_barcos.addWidget(self.label_2, 0, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.grilla_barcos.addWidget(self.label_7, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.grilla_barcos.addWidget(self.label_8, 1, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.grilla_barcos.addWidget(self.label_9, 1, 7, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.grilla_barcos.addWidget(self.label, 0, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.grilla_barcos.addWidget(self.label_22, 4, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_23.setText("")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.grilla_barcos.addWidget(self.label_23, 4, 6, 1, 1)
        self.label_24 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_24.setText("")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.grilla_barcos.addWidget(self.label_24, 4, 7, 1, 1)
        self.label_25 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.grilla_barcos.addWidget(self.label_25, 4, 8, 1, 1)
        self.label_26 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.grilla_barcos.addWidget(self.label_26, 4, 9, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.grilla_barcos.addWidget(self.label_13, 2, 6, 1, 1)




        ####################################################### GRILLA DE ATAQUE ###########################################################

        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(730, 280, 341, 331))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grilla_de_ataque = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grilla_de_ataque.setContentsMargins(0, 0, 0, 0)
        self.grilla_de_ataque.setObjectName("grilla_de_ataque")
        self.push12 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push12.setFont(font)
        self.push12.setObjectName("push12")
        self.grilla_de_ataque.addWidget(self.push12, 2, 1, 1, 1)
        self.push1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push1.setFont(font)
        self.push1.setObjectName("push1")
        self.grilla_de_ataque.addWidget(self.push1, 0, 0, 1, 1)
        self.push3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push3.setFont(font)
        self.push3.setObjectName("push3")
        self.grilla_de_ataque.addWidget(self.push3, 0, 2, 1, 1)
        self.push2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push2.setFont(font)
        self.push2.setObjectName("push2")
        self.grilla_de_ataque.addWidget(self.push2, 0, 1, 1, 1)
        self.push5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push5.setFont(font)
        self.push5.setObjectName("push5")
        self.grilla_de_ataque.addWidget(self.push5, 0, 4, 1, 1)
        self.push4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push4.setFont(font)
        self.push4.setObjectName("push4")
        self.grilla_de_ataque.addWidget(self.push4, 0, 3, 1, 1)
        self.push7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push7.setFont(font)
        self.push7.setObjectName("push7")
        self.grilla_de_ataque.addWidget(self.push7, 1, 1, 1, 1)
        self.push6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push6.setFont(font)
        self.push6.setObjectName("push6")
        self.grilla_de_ataque.addWidget(self.push6, 1, 0, 1, 1)
        self.push8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push8.setFont(font)
        self.push8.setObjectName("push8")
        self.grilla_de_ataque.addWidget(self.push8, 1, 2, 1, 1)
        self.push11 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push11.setFont(font)
        self.push11.setObjectName("push11")
        self.grilla_de_ataque.addWidget(self.push11, 2, 0, 1, 1)
        self.push9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push9.setFont(font)
        self.push9.setObjectName("push9")
        self.grilla_de_ataque.addWidget(self.push9, 1, 3, 1, 1)
        self.push13 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push13.setFont(font)
        self.push13.setObjectName("push13")
        self.grilla_de_ataque.addWidget(self.push13, 2, 2, 1, 1)
        self.push14 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push14.setFont(font)
        self.push14.setObjectName("push14")
        self.grilla_de_ataque.addWidget(self.push14, 2, 3, 1, 1)
        self.push10 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push10.setFont(font)
        self.push10.setObjectName("push10")
        self.grilla_de_ataque.addWidget(self.push10, 1, 4, 1, 1)
        self.push16 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push16.setFont(font)
        self.push16.setObjectName("push16")
        self.grilla_de_ataque.addWidget(self.push16, 3, 0, 1, 1)
        self.push19 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push19.setFont(font)
        self.push19.setObjectName("push19")
        self.grilla_de_ataque.addWidget(self.push19, 3, 3, 1, 1)
        self.push18 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push18.setFont(font)
        self.push18.setObjectName("push18")
        self.grilla_de_ataque.addWidget(self.push18, 3, 2, 1, 1)
        self.push15 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push15.setFont(font)
        self.push15.setObjectName("push15")
        self.grilla_de_ataque.addWidget(self.push15, 2, 4, 1, 1)
        self.push17 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push17.setFont(font)
        self.push17.setObjectName("push17")
        self.grilla_de_ataque.addWidget(self.push17, 3, 1, 1, 1)
        self.push20 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push20.setFont(font)
        self.push20.setObjectName("push20")
        self.grilla_de_ataque.addWidget(self.push20, 3, 4, 1, 1)
        self.push21 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push21.setFont(font)
        self.push21.setObjectName("push21")
        self.grilla_de_ataque.addWidget(self.push21, 4, 0, 1, 1)
        self.push22 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push22.setFont(font)
        self.push22.setObjectName("push22")
        self.grilla_de_ataque.addWidget(self.push22, 4, 1, 1, 1)
        self.push23 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push23.setFont(font)
        self.push23.setObjectName("push23")
        self.grilla_de_ataque.addWidget(self.push23, 4, 2, 1, 1)
        self.push24 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push24.setFont(font)
        self.push24.setObjectName("push24")
        self.grilla_de_ataque.addWidget(self.push24, 4, 3, 1, 1)
        self.push25 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(24)
        self.push25.setFont(font)
        self.push25.setObjectName("push25")
        self.grilla_de_ataque.addWidget(self.push25, 4, 4, 1, 1)

        #########################################   CONSTRUCCION DE TABLA   #############################################

        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(60, 151, 621, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.tabla_h = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.tabla_h.setContentsMargins(0, 0, 0, 0)
        self.tabla_h.setObjectName("tabla_h")
        self.label_27 = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        self.label_27.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(True)
        self.label_27.setScaledContents(True)
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.tabla_h.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_28.setFont(font)
        self.label_28.setAutoFillBackground(True)
        self.label_28.setScaledContents(True)
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.tabla_h.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_29.setFont(font)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.tabla_h.addWidget(self.label_29, 0, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_30.setFont(font)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.tabla_h.addWidget(self.label_30, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tabla_h.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(26, 191, 31, 531))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.tabla_v = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.tabla_v.setContentsMargins(0, 0, 0, 0)
        self.tabla_v.setObjectName("tabla_v")
        self.label_35 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_35.setFont(font)
        self.label_35.setAutoFillBackground(True)
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.tabla_v.addWidget(self.label_35, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_34.setFont(font)
        self.label_34.setAutoFillBackground(True)
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.tabla_v.addWidget(self.label_34, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_33.setFont(font)
        self.label_33.setAutoFillBackground(True)
        self.label_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.tabla_v.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_32.setFont(font)
        self.label_32.setAutoFillBackground(True)
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.tabla_v.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Gloucester MT Extra Condensed")
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setAutoFillBackground(True)
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.tabla_v.addWidget(self.label_31, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setEnabled(False)
        self.line.setGeometry(QtCore.QRect(60, 181, 621, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setEnabled(False)
        self.line_2.setGeometry(QtCore.QRect(50, 191, 20, 531))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_3.setEnabled(False)
        self.line_3.setGeometry(QtCore.QRect(60, 280, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_4.setEnabled(False)
        self.line_4.setGeometry(QtCore.QRect(60, 392, 621, 20))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_5.setEnabled(False)
        self.line_5.setGeometry(QtCore.QRect(60, 501, 621, 20))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_6.setEnabled(False)
        self.line_6.setGeometry(QtCore.QRect(60, 610, 621, 16))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_7.setEnabled(False)
        self.line_7.setGeometry(QtCore.QRect(60, 712, 621, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_8.setEnabled(False)
        self.line_8.setGeometry(QtCore.QRect(665, 191, 31, 531))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_9.setEnabled(False)
        self.line_9.setGeometry(QtCore.QRect(539, 191, 41, 531))
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_10.setEnabled(False)
        self.line_10.setGeometry(QtCore.QRect(169, 191, 31, 531))
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_11.setEnabled(False)
        self.line_11.setGeometry(QtCore.QRect(289, 191, 41, 531))
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_12.setEnabled(False)
        self.line_12.setGeometry(QtCore.QRect(419, 191, 31, 531))
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")


        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        #Le da los nombres correspondientes a los elementos de la interfaz:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_27.setText(_translate("MainWindow", "B"))
        self.label_28.setText(_translate("MainWindow", "C"))
        self.label_29.setText(_translate("MainWindow", "D"))
        self.label_30.setText(_translate("MainWindow", "E"))
        self.label_5.setText(_translate("MainWindow", "A"))
        self.label_35.setText(_translate("MainWindow", "5"))
        self.label_34.setText(_translate("MainWindow", "4"))
        self.label_33.setText(_translate("MainWindow", "1"))
        self.label_32.setText(_translate("MainWindow", "3"))
        self.label_31.setText(_translate("MainWindow", "2"))
        self.titulo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#1b437e;\">BATTLESHIP</span></p></body></html>"))
        self.aleatorizar_barcos.setText(_translate("MainWindow", "Aleatorizar barcos"))
        self.inicial_juego.setText(_translate("MainWindow", "Inicializar juego"))
        self.titulo_2.setText(_translate("MainWindow", "Realice el ataque"))
        self.explosion.setText(_translate("MainWindow", "Explosión del material"))
        self.push12.setText(_translate("MainWindow", "B3"))
        self.push1.setText(_translate("MainWindow", "A1"))
        self.push3.setText(_translate("MainWindow", "C1"))
        self.push2.setText(_translate("MainWindow", "B1"))
        self.push5.setText(_translate("MainWindow", "E1"))
        self.push4.setText(_translate("MainWindow", "D1"))
        self.push7.setText(_translate("MainWindow", "B2"))
        self.push6.setText(_translate("MainWindow", "A2"))
        self.push8.setText(_translate("MainWindow", "C2"))
        self.push11.setText(_translate("MainWindow", "A3"))
        self.push9.setText(_translate("MainWindow", "D2"))
        self.push13.setText(_translate("MainWindow", "C3"))
        self.push14.setText(_translate("MainWindow", "D3"))
        self.push10.setText(_translate("MainWindow", "E2"))
        self.push16.setText(_translate("MainWindow", "A4"))
        self.push19.setText(_translate("MainWindow", "D4"))
        self.push18.setText(_translate("MainWindow", "C4"))
        self.push15.setText(_translate("MainWindow", "E3"))
        self.push17.setText(_translate("MainWindow", "B4"))
        self.push20.setText(_translate("MainWindow", "E4"))
        self.push21.setText(_translate("MainWindow", "A5"))
        self.push22.setText(_translate("MainWindow", "B5"))
        self.push23.setText(_translate("MainWindow", "C5"))
        self.push24.setText(_translate("MainWindow", "D5"))
        self.push25.setText(_translate("MainWindow", "E5"))
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = battleship()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
